### PR TITLE
Added various block settings to control grid columns

### PR DESCRIPTION
**Pull request by treyhendon**

### CODE REVIEW

**Comment by cabal95** [comment]
What do you think of making the PersonLink and GroupMember link process as Lava and make `{Id}`, `{GroupId}`, and `{GroupMemberId}` available merge fields to both?  e.g. `/Person/{Id}`. I'm thinking that would simplify the code a little and provide better flexibility if they wanted to do something like `/Person/{Id}/Contributions`.

Also, was the ability to show/hide all the grid action buttons something that was specifically requested? If those are really needed (as opposed to "just because") I'm wondering if we should move them to the Advanced tab to clean up the block settings UI a bit.

**Comment by treyhendon** [comment]
Yeah, I'm totally in favor of doing that via lava.

Hiding individual actions per block instance was a specific request, but I think shifting to the Advanced tab would be totally fine.

I can get both of those recoded next week if you'd like.

**Comment by cabal95** [comment]
Sounds good, thanks!

**Comment by cabal95** [comment]
Hey Trey, just realized this was still pending open. Did you ever have a chance to do those tweaks?

**Comment by treyhendon** [comment]
So sorry!  I lost eyes on this one.  Just made those changes and pushed up here.

**Comment by cabal95** [comment]
Yea I lost track of this too :).  Thanks for the changes. I'll work on getting these pulled in next week and hopefully submitting the block to core.

**Pull request merged**
